#!/bin/bash

echo "BIORAIZ Deployment Checklist"
echo "============================="
echo ""
echo "Frontend (Cloudflare Pages):"
echo "  [ ] npm run build -w frontend"
echo "  [ ] Verifica ./frontend/dist"
echo "  [ ] Conecta a Cloudflare Pages"
echo ""
echo "Backend (Railway):"
echo "  [ ] npm run build -w api"
echo "  [ ] DATABASE_URL configurada"
echo "  [ ] Variables de entorno en Railway dashboard"
echo "  [ ] Script init.sh ejecutado"
echo ""
echo "Workers (Cloudflare):"
echo "  [ ] npm run deploy -w workers"
echo "  [ ] wrangler.toml configurado"
echo ""
echo "Dominio (bioraiz.net):"
echo "  [ ] Nameservers: nat.ns.cloudflare.com / noel.ns.cloudflare.com"
echo "  [ ] CNAME @ → bioraiz-website.pages.dev"
echo "  [ ] CNAME www → bioraiz-website.pages.dev"
echo "  [ ] CNAME api → workers.bioraiz.workers.dev"
echo ""
echo "Emails:"
echo "  [ ] Resend/SendGrid API key configurada"
echo "  [ ] Dominio verificado (bioraiz.net)"
echo "  [ ] Admin email: hola@bioraiz.net"
echo ""
echo "GitHub Actions:"
echo "  [ ] Secrets configurados"
echo "  [ ] deploy.yml en .github/workflows"
echo ""
echo "Testing:"
echo "  [ ] npm run lint"
echo "  [ ] npm run type-check"
echo ""
echo "✓ Checklist completado: Listo para deploy"
